{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "service-chat.fullname" . }}-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: service-chat.rules
      rules:
        - alert: ServiceChatHigh5xxErrorRate
          expr: |
            100 *
            sum(rate(http_server_requests_seconds_count{
              application="service-chat",
              status=~"5.."
            }[1m]))
            /
            sum(rate(http_server_requests_seconds_count{
              application="service-chat"
            }[1m]))
            > 5
          for: 1m
          labels:
            severity: critical
            service: service-chat
          annotations:
            summary: "Service Chat 5xx error rate high"
            description: "service-chat 5xx error rate > 5% for 1 minute"
  {{- end }}

