apiVersion: v1
kind: ConfigMap
metadata:
  name: service_chat-config
data:
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "service_chat_db"
  application.yml: |
    spring:
      application:
        name: service_chat-service
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
